services:
  fastmcp:
    build:
      context: .
      dockerfile: Dockerfile.fastmcp
    ports:
      - "8000:8000"
    environment:
      - AWS_REGION=us-east-2
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
